### PR TITLE
Multiple Improvements and Fixes (again)

### LINKED ISSUE #30: Add Secure Value Masking
Add a new argument to `dumps` and `to_tree` that can mask secure values.

### LINKED ISSUE #32: Empty ListField not properly dealt with
If a ListField is left empty in the config, the value is left `None` and causes an error when trying to output to an dict or JSON.

```python
from cincoconfig import *

schema = Schema()

schema.something = ListField()

config = schema()
print(config.dumps(format='json', pretty=True).decode())
```
causes the error:
```
Traceback (most recent call last):
  File ".\configtest.py", line 9, in <module>
    print(config.dumps(format='json', pretty=True).decode())
  File "C:\Users\user\Documents\test\venv\lib\site-packages\cincoconfig\config.py", line 518, in dumps
    return formatter.dumps(self, self.to_tree(virtual=virtual, secure_mask=secure_mask))
  File "C:\Users\user\Documents\test\venv\lib\site-packages\cincoconfig\config.py", line 675, in to_tree
    value = field.to_basic(self, field.__getval__(self))
  File "C:\Users\user\Documents\test\venv\lib\site-packages\cincoconfig\fields.py", line 679, in to_basic
    return list(value)
TypeError: 'NoneType' object is not iterable
```

### LINKED ISSUE #33: Booleans in JSON are accepted in numerous non-Boolean field types
For example, having a config file `testme.json`:
```
{
    "something": true
}
```

This value is considered valid for:
* `IntField` (considered a 1)
* `PortField`(considered a 1)
* `HostnameField`(converted to `"0.0.0.1"`)
* `StringField`(just converted to string)
* `FilenameField`(also just converted to a string)
* `IPv4NetworkField`(Converted to `"0.0.0.1/32"`)

### PR DESCRIPTION
**Pull request by ameily**
- Closes #30 - Mask secure / sensitive values in `to_tree()/dumps()`
- Closes #33 - Enforce string value type
- Closes #32 - Handle empty list fields (refactor)

### CODE REVIEW

**Comment by ameily** [comment]
@vix597 This adds two new parameters to `Config.to_tree/dumps`

- `virtual`: include virtual fields in the output
- `secure_mask`: mask secure values in the output

`secure_mask` is either a single character or multiple characters and works like this:

```python
>>> config.to_tree(secure_mask='*')['secure_value']
'***********'

>>> config.to_tree(secure_mask='<secret>')['secure_value']
'<secret>'

>>> config.to_tree(secure_mask='')['secure_value']
''
```

**Comment by vix597** [comment]
Epic!

**Comment by vix597** [comment]
Two things:

1. I'm not 100% clear on the use of the new `virtual` option.
1. I looks like there's an exception masking secure fields when the field isn't set (e.g. field is None):

```
  File "config.py", line 667, in to_tree
    value = self._data[key].to_tree(virtual=virtual, secure_mask=secure_mask)
  File "config.py", line 671, in to_tree
    value = secure_mask * len(value)
TypeError: object of type 'NoneType' has no len()
```

**Comment by vix597** [comment]
Latest push fixes both issues we were seeing.

**Comment by vix597** [comment]
@ameily - Make sure you pull if you're gonna work on this - I fixed the linting error. Just an unused import.

**Comment by vix597** [comment]
damn - Still errors with mypy. Those one are all you lol

**Comment by ameily** [comment]
@vix597 By default, read-only virtual fields do not add any items to the config `_data` dict, so they won't be included in the `to_tree()` output. Specifying `virtual=True`, will include these virtual field values in the tree. For example:

```python
>>> from cincoconfig import *
>>> from datetime import datetime
>>> schema = Schema()
>>> schema.last_write_time = VirtualField(getter=lambda cfg: datetime.now().isoformat())
>>> config = schema()
>>>
>>> config.to_tree()
{}
>>> config.to_tree(virtual=True)
{'last_write_time': '2020-11-05T18:54:52.258131'}
```

I also added a new Field attribute, `sensitive` that, when set to True, can be masked with the `sensitive_mask` parameter. So, it'll apply to SecureFields or any sensitive field.

**Pull request merged**
