### PR TITLE
Issue #2 (ameily) - Secure and Challenge Fields

### PR DESCRIPTION
**Pull request by ameily**

### CODE REVIEW

**Comment by ameily** [comment]
@vix597 Alright, finally got around to reworking the challenge/secure field based on our discussion on the other PR. I pulled out the keyfile into it's own class. Now, each config can have its own keyfile location or, if it isn't set, it'll fall back to using the key file of the parent config. If the root config doesn't have the key file set then it'll use the default location, which is `~/.cincokey`. Users will be able to change the default location prior to loading the first config from disk since we dereference the key file location on first access. This will allow applications and libraries that both use cincoconfig to use the same or different cincokey files.

The keyfile is only valid within a `with` statement. The `with` will open the keyfile on disk, read it, and cache it until all `with` statements have ended. This allow us to only read the keyfile once when loading or saving mutliple secure fields.

```python
config1 = schema()
with config._keyfile as ctx:
    secret = ctx.encrypt(b'hello, world', method='aes')
```

The keyfile and encryption are all internal and users of cincoconfig should never have to directly access it. To change the default location of the cincokey:

```python
from cincoconfig import BaseConfig

BaseConfig.DEFAULT_CINCOKEY_FILEPATH = '/path/to/default/.key'
```

Feel free to review and let me know what you think.

**Comment by vix597** [comment]
Looks really good. Did any of my code survive? lol.

**Comment by ameily** [comment]
> Looks really good. Did any of my code survive? lol.

Yeah most of it did in spirit. It was mostly restructuring it to two fields and pulling the key file into it's own class so that the key is read once during load/save.

**Comment by vix597** [comment]
Yeah man! it looks fucking awesome. It's way cleaner this way. Merge that shit. And kill my shitty branch.

**Comment by ameily** [comment]
I also added:

- New `IncludeField` to include multiple configuration files (#5)
- Getting and setting config values by their path (#6)
  ```python
  >>> config['db.port'] = 23
  >>> print(config['db.port'])
  23
  >>> print(config.db.port)
  23
  ```

**Pull request merged**
